import { clsx } from "clsx";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { PropsWithChildren } from "react";

import styles from "./MainLayout.module.css";

// Maybe I should decouple font from layout on body,
// but there is only one layout, so it's good enough for me
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

const globalTitle = "greenscrens.ai";

type MainLayoutProps = PropsWithChildren<{
    title?: string
}>;

export function MainLayout({ children, title }: MainLayoutProps) {
    return (
        <>
            <Head>
                <title>{title || globalTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={clsx(poppins.className, styles.main)}>{children}</main>
        </>
    );
};
